# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0f713162c5ae02a13ee20f1b7d1b5e4ec01fcd20b001f919d65adda8ad14c2c9aa24144a8d59ebb35dfce39eb6be57c7c543929f06ae3a7a646fbdaab5eced4

test:
  secret_key_base: 214f9acfe12e4e14d770935a39a65baddaf5f8d58b1b16d046a9f60cf14742812d090ed73d5a39a995750e25db5230b926abd2ae877f9dd4654f6d9a3819b02e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
